### ISSUE TITLE
App layout crash in iOS (can reproduce at will)

### ISSUE THREAD

**Issue by sivolc73** [bluecherrydvr/unity#168]
When using the third or fourth camera layout the app turn gray and I can't do anything other than swipe and go back to other menus.
I tried guess clicking on the 1 and 2 buttons to see if it get back but nothing, it stays gray even if I change tab in the app, restart the app or the phone, It does it with or without a server added.

**I need to reinstall the app when it happen.**

In the first two layouts everything is fine.

| First two layouts  | Third or fourth layout | layout crashed |
| ------------- | ------------- | ------------- |
| ![image](https://github.com/bluecherrydvr/unity/assets/7545109/9f45cf40-cdd3-4d07-bb0c-e06e8864bd62)  |  ![image](https://github.com/bluecherrydvr/unity/assets/7545109/00974cb2-e5e2-4c18-9785-87bd5057087f)  | ![image](https://github.com/bluecherrydvr/unity/assets/7545109/fa40aabc-586f-42a5-b1f1-599265221242) |

# App version 3.0.012
iOS 16.6.1 iPhone SE 2020

**Comment by curtishall** [comment]
I can also reproduce this @bdlukaa
