### ISSUE TITLE
Navigation to downloaded content blocked by video playback

### ISSUE THREAD

**Issue by sivolc73** [bluecherrydvr/unity#172]
When you download a file from the event panel you can't navigate directly to the download folder with the button view in downloads if you are playing back the video, On windows as soon as you close video playback you are on the download folder, I guess the button don't close the playback panel and stay in overlay. On  linux when I press the back button of the playback windows the app crash and I have to terminate the process.

![Capture d’écran du 2023-11-03 08-21-32](https://github.com/bluecherrydvr/unity/assets/7545109/168b4f1c-d7bd-4dbb-bc45-69781a5bc225)

Version: 3.0.0-beta 13 (Windows 10 and PopOS 22.04 LTS) (for both appimage and .DEB install)

**Comment by curtishall** [comment]
Thanks for the report.  I'm creating a separate bug for 'linux when I press the back button of the playback windows the app crash and I have to terminate the process.'
