### ISSUE TITLE
Allow the timeline cursor to stick to next event during playback

### ISSUE THREAD

**Issue by sivolc73** [bluecherrydvr/unity#259]
When dealing with short events (30s to 2minutes) It is hard to go to the start of the event, It would be useful that the cursor when you click an empty spot of the timeline just jump to the start of the next event.

It could also jump from events to events when it reach the end of an event, it would be less awkward when searching for something on a long period of not a lot of activity of motion detection. 

I also wonder if a skip event button of some sort was in the plans?

**Comment by bdlukaa** [comment]
You can zoom in the timeline using your mouse scroll-wheel.

https://github.com/user-attachments/assets/03226efb-2f76-493f-b830-7c3ec41452bb

> I also wonder if a skip event button of some sort was in the plans?

I wonder how this would work on a scenario of multiple devices being displayed.

**Comment by sivolc73** [comment]
When the timeline is long and sparse it get a bit annoying to zoom in and out and drag, you get lost easily, I imagine on mobile it get worst but I haven't played with it a ton yet.

![image](https://github.com/user-attachments/assets/3cd24bca-0629-49dd-ab84-5781403705b3)

Maybe the next button could just go from event start to event start trough the timeline, with one stream selected it would mean from event to event, with multiple stream it would jump to the start of the next event of any stream.

Alternatively the selected (clicked?) stream timeline would be the "master" possibly slightly highlighted or framed differently so when you click next now it goes trough this particular stream events (the others streams playback would just follow)

**Comment by bdlukaa** [comment]
> I imagine on mobile it get worst

On mobile we use different screens and the events are displayed sequentially, one after another.

The "jump" button is a good idea. The user can just press it to skip the empty period in the timeline. 
We can also add an option in Settings to automatically skip empty periods.

**Comment by sivolc73** [comment]
> We can also add an option in Settings to automatically skip empty periods.

I like the idea of this being optional too, I think this it could suit different needs without annoying someone that try to play again and again the same event to see something. So default could be continuous time and in the options a "from event to event playback"

The skip would be nice also to get back to the start of an event I don't know if you had forward and backward skip in mind? 
Like music players with double tap on back to see start of previous event, it would be intuitive to new users I think.

**Comment by bdlukaa** [comment]
Hello @sivolc73! Can you check the latest [`bleeding_edge`](https://github.com/bluecherrydvr/unity/releases/tag/bleeding_edge) release? thanks

**Comment by sivolc73** [comment]
Hi @bdlukaa Oh this is cool :) I like the skip, super pleasant to skip trough footage to find someone or something that appear or disappear. I love the continuous play that skip empty part of the timeline.

As a side note, the app in dark mode keep the timeline cursor black which make it hard to track, maybe the cursor should become pale when in dark mode? Or maybe even as an accessibility feature the cursor could have a color selector in the settings (very not high priority feature but a nice touch)
![image](https://github.com/user-attachments/assets/8ca921dd-0241-4d69-a59f-a87419e8b11e)
 
One thing that bother me is that when you go to the timeline I can still hear the live feed audio, maybe the live feeds should be paused automatically? It would also allow for more bandwidth to be used to get footage and decoding to be a bit more smooth on playback.

While skipping back and forward I can easily trigger this error:

```
flutter: FINE: 2024-09-07 16:57:53.347165: default FrameReader0x7191f432b660 request to pause 1, loaded: 0.
flutter: FINE: 2024-09-07 16:57:53.347170: default FrameReader0x7191f432b660 state: 0=>2=>2, 0
flutter: FINE: 2024-09-07 16:57:53.347178: 0x7191f4483e30 player.set(2)
flutter: FINE: 2024-09-07 16:57:53.347183: 0x7191f44a0740 virtual void mdk::MediaControlPush::setState(PlaybackState)@1068 requested state 2=>2, current state 0. status: 0X41
flutter: FINE: 2024-09-07 16:57:53.347188: ALSA ERROR@284 snd_pcm_pause(pcm_, value) (0XFFFFFFFB): Input/output error
flutter: FINE: 2024-09-07 16:57:53.347194: 
flutter: FINE: 2024-09-07 16:57:53.347199: default FrameReader0x7191f432b660 request to pause 1, loaded: 0.
operator()425 postCObject error
operator()425 postCObject error
Erreur de segmentation (core dumped)

```
(this is my personal machine running popOS 22.04, will try everything at work on my Ubuntu machine Tuesday :) 


But yeah this is really nice, super happy to see this so fast!

**Comment by bdlukaa** [comment]
Thank you for your feedback! For other requests, please open another issue. Thanks
