### ISSUE TITLE
Allow camera order change in the timeline

### ISSUE THREAD

**Issue by sivolc73** [bluecherrydvr/unity#265]
When using the timeline the order of the camera seems kind of random, when using a large angle camera which use two sensors it make for a weird experience, I tried enabling one first then the other and the reverse but it stays the same.

I is not experience breaking but maybe it could just keep track of the order you tick the cameras in the filter panel?

![Capture d’écran du 2024-09-11 09-34-31](https://github.com/user-attachments/assets/dfadd340-518e-4c5e-a9aa-967a451d9ed4)

**Comment by bdlukaa** [comment]
The order is determined by what camera returns the events response first.

I will see the options to make it reorderable, like the Devices View
