### ISSUE TITLE
Add edit lock to live view

### ISSUE THREAD

**Issue by sivolc73** [bluecherrydvr/unity#282]
I watched my coworkers interact with the app and realized they mistake the camera list for the view selector quite often when trying to change view, maybe there could be a lock icon next to the "add all to view" button that collapse the camera list? It would visually direct users to the view list instead.

![image](https://github.com/user-attachments/assets/88e70bb1-c6d1-41af-b476-bcfeaf27a6d0)

**Comment by bdlukaa** [comment]
I think the lock should be applied to each layout. The user locks the layout and no cameras will be added to it. What do you think?

**Comment by sivolc73** [comment]
Hum, I'm not entirely sure, this solution does make sense to me, a tech person. But at the same time I spotted this problem from watching other non technical people who thought that the way to change view is to click another camera (Which also make some intuitive sense too) So I thought that having some way to collapse or hide the camera list would help with that.

If the views are locked and the cameras list still visible then you have a clickable camera list that does nothing when you press them? Or would the list appear when you are viewing a layout which isn't locked?

**Comment by bdlukaa** [comment]
> So I thought that having some way to collapse or hide the camera list would help with that.

An option to collapse the camera list will be available as soon as #284 gets merged.

This way we could have locked layouts, which will block adding new cameras and reordering them.

**Comment by sivolc73** [comment]
Fantastic! Thanks!
