### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by sivolc73** [bluecherrydvr/unity#292]
I don't know if it was on the roadmap but I would really like to see some keyboard shortcuts:

- Fullscreen (F11) : going to settings to change that is a bit of a pain, especially if I need to just get out of fullscreen to change something elsewhere on the computer

- Immersive (maybe F12 or something) when I remote in a computer (like a dedicated kiosk computer with no keyboard/mouse) it can be hard to hit just right the top part of the remote screen window to make the top bar appear.

- Views: It would be useful to have something like a CTRL-1...2...3 to launch and display the corresponding live view, from anywhere in the app. My motivation for this feature would be to be able to easily script some actions by triggering keyboard events. Let's say I have some system that receive a doorbell event I could just ctrl-2 to the door camera without any need for an API on any complex mechanism from the app. I would also assume that going directly to a view would stop the cycling mode.

- Next/Toggle cycling: useful to resume cycling after an event

- Mute: Mute everything all at once

**Comment by bdlukaa** [comment]
I like the idea of having global shortcuts, such as F11 and F12 for fullscreen and immersive modes, respectively.

| Key | Action |
| ---- | ------- |
| Alt + 1; home | Navigate to Layouts screen |
| Alt + 2 | Navigate to Timeline of Events screen |
| Alt + 3 | Navigate to Event History screen |
| Alt + 4 | Navigate to Add Server screen |
| Alt + 5 | Navigate to Downloads screen |
| Alt + 6 | Navigate to Settings screen |
| F11 | enter/exit fullscreen |
| Shift + F11 | enter/exit immersive mode |

I also like having control of the current selected layout/screen using ctrl + n, like Slack. This would apply to the Layouts view and Settings Page.

On the Layouts screen, these would be the shortcuts:

| Key | Action |
| ---- | ------- |
| Ctrl + {1, 3, 4, 5, 6, 7, 8, 9} | Set layout |
| Ctrl + Shift + C | Toggle Layout Cycling |
| Ctrl + B | Toggle Sidebar |
| Ctrl + N | New Layout |
| Ctrl + Tab | Next layout |
| Ctrl + L | Un/lock current layout |

We already have a good set of keyboard shortcuts on the Timeline of Events screen. They are:
| Key | Action |
| --- | ------- |
| > | seek forward |
| < | seek backward |
| space; play/pause | play or pause |
| play | play |
| pause; stop | pause |
| F5 | reload |
| media next | next event |
| media previous | previous event |
| step forward | step forward |
| step backward | step backward |
| home; 0 | seek to beginning |
| 1, 2, 3, 4, 5, 6, 7, 8, 9 | seek to position |
| end | seek to end |
| m | mute |
| arrow up | increase volume |
| arrow down | decrease volume |

I personally do not like the mute shortcut. It can lead to unexpected behavior. I will also consider adding a few warnings to the user saying the action happened, like "Entered full screen mode."

**Comment by sivolc73** [comment]
I think it's a pretty good coverage for shortcut needs, I like the shift + F11 for immersive, very intuitive and one less key to learn. 
Maybe I would add a F5 refresh key to the layout that would reload the cameras.

I think the "Set layout" should stop the cycling, this way at least one shortcut can blindly set a known state for the cycling since toggling can get out of sync in the case of scripting an action.

I don't know if you gave thoughts about the documentation of the shortcuts, maybe F1 could show an overlay or popup style windows with the list of wither all the shortcuts of the relevant shortcuts for the actually displayed screen? 
Maybe even by holding F1, I don't remember which software did that but I appreciated the fact that F1 was helpful but still would not open something I have to close if I hit F1 by accident while using escape.

**Comment by bdlukaa** [comment]
> I don't know if you gave thoughts about the documentation of the shortcuts, maybe F1 could show an overlay or popup style windows with the list of wither all the shortcuts of the relevant shortcuts for the actually displayed screen?
Maybe even by holding F1, I don't remember which software did that but I appreciated the fact that F1 was helpful but still would not open something I have to close if I hit F1 by accident while using escape.

I thought to let the shortcuts on the Settings page, where users would be able to change them as they need. Maybe F1 would redirect to the Help page? I don't think F1 would be suitable for the shortcuts.

**Comment by sivolc73** [comment]
> > I don't know if you gave thoughts about the documentation of the shortcuts, maybe F1 could show an overlay or popup style windows with the list of wither all the shortcuts of the relevant shortcuts for the actually displayed screen?
> > Maybe even by holding F1, I don't remember which software did that but I appreciated the fact that F1 was helpful but still would not open something I have to close if I hit F1 by accident while using escape.
> 
> I thought to let the shortcuts on the Settings page, where users would be able to change them as they need. Maybe F1 would redirect to the Help page? I don't think F1 would be suitable for the shortcuts.

Oh I didn't realized the shortcuts would be customizable, that's great then! No need for a help mechanism.
