### ISSUE TITLE
Accept command line options for display and layout

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/unity#32]
Currently we only support a fullscreen command line option.  Adding a command line option would be useful for customers with multiple monitors / layouts:

For example: bluecherryclient.exe [ -l "layout name:monitor_number" ]

**Comment by bdlukaa** [comment]
A list of command lines that should be accepted:

* `--[no]-fullscreen`: starts the app in Fullscreen;
  * `--[no]-immersive`: starts the app in Immersive Mode
    * `--kiosk`: only allow users to access the Layouts View;
* `--[no]-wakelock`: keeps the screen active when enabled;
* `--[no]-cycle`: whether the layout cycle is enabled;
* `--layout="name"`: starts at the specified layout;
  * `--layout-index=0`: starts at the specified layout index;
* `--theme=dark,light,system`
