### ISSUE TITLE
Distribute on different Linux platforms and stores

### ISSUE THREAD

**Issue by nixfu** [bluecherrydvr/unity#33]
Since you guys seem great about trying to maintain Linux support in the client, I would suggest you look into creating a Linux AppImage package.   

It makes supporting multiple Linux distros MUCH easier.

https://appimage.org/

This actually might be a way to package the existing client to work on newer systems that come with Qt5 now but still make them able to run the client because the AppImage can contain its own Qt4 libs inside it.  You could create the  AppImage on older Ubuntu with Qt4, but people would be able to run it on their newer Ubuntu 20, or Arch Linux systems too.

It would take some of the pressure off having to immediately migrate to Qt5 for instance.

**Comment by bdlukaa** [comment]
We are now distributing for the snapstore. [Check it out](https://snapcraft.io/bluecherry-client).
