### ISSUE TITLE
Desktop client will not close all the way, has to be killed via task manager

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/unity#49]
1. If you exit from the program in the history viewer by clicking the X, a unity process is left running in the task manager. I needed to manually remove the nonresponsive unity process before starting the program again.

_Originally posted by @MathewWMoore in https://github.com/bluecherrydvr/unity/discussions/47#discussioncomment-4779652_

**Comment by bdlukaa** [comment]
Related issues:
 * https://github.com/flutter/flutter/issues/66631

**Comment by bdlukaa** [comment]
With some investigation, it looks like a dll is keeping the app alive. Working on a fix for it!
