### ISSUE TITLE
Timezone uses GMT instead of local timezone

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/unity#50]
I believe the timestamp on the Events player does not account for the local timezone. I'm getting a date in the future :)

_Originally posted by @MathewWMoore in https://github.com/bluecherrydvr/unity/discussions/47#discussioncomment-4779652_

**Comment by bdlukaa** [comment]
For this, would it be better to have a setting in the Settings screen or just enable it automatically?

**Comment by curtishall** [comment]
Enable automatically please
