### ISSUE TITLE
dart_vlc_plugin.dll was not found

### ISSUE THREAD

**Issue by dragoneye65** [bluecherrydvr/unity#63]
This message pops up when I try to run the client.
![image](https://user-images.githubusercontent.com/4040093/216285999-8a3cdf1e-0189-4f4c-b27e-a1a99c99c3f6.png)

Do we have to download the flutter and dart SDK packages to run this?

Regards

**Comment by curtishall** [comment]
@bdlukaa

**Comment by bdlukaa** [comment]
Can you try with the latest version?

**Comment by dragoneye65** [comment]
The system error is gone, I can run the application now. Great work. Thank you.

Regards

**Comment by dragoneye65** [comment]
Cannot find any devices on the server tho :)
![image](https://user-images.githubusercontent.com/4040093/216728849-7620e246-4759-44bf-8caf-b9bc38726d73.png)

**Comment by curtishall** [comment]
Are you using Version 2 or 3?

**Comment by dragoneye65** [comment]
Version 3

**Comment by curtishall** [comment]
Can you see the devices in the client and the number of numbers is 0 or can you not see *any* in the device list?

**Comment by dragoneye65** [comment]
I don't see any devices anywhere in this client "unity" app, in my "Bluecherry 2.2.9 client" all my devices are showing and are in daily use, 8 devices in total.

**Comment by dragoneye65** [comment]
![Uploading image.png…]()
:)

**Comment by dragoneye65** [comment]
![image](https://user-images.githubusercontent.com/4040093/216774661-47d50c54-3ab4-4f1a-ba57-3685080abbfa.png)

**Comment by dragoneye65** [comment]
I am getting the "events" tho
![image](https://user-images.githubusercontent.com/4040093/216774849-8ee96e12-d086-4fe1-ad47-341415f154f7.png)

**Comment by dragoneye65** [comment]
But no devices
![image](https://user-images.githubusercontent.com/4040093/216774891-7bd879b6-0716-4436-8235-a2044fef7b9c.png)

**Comment by dragoneye65** [comment]
![image](https://user-images.githubusercontent.com/4040093/216774908-bbf34929-9466-4ba4-b1b2-777d1195e479.png)

**Comment by dragoneye65** [comment]
In the old client I have everything working.
![image](https://user-images.githubusercontent.com/4040093/216776377-b51adcab-1deb-4b52-9ab8-fd56a5b3d722.png)

**Comment by curtishall** [comment]
I can't reproduce this with version 3 of the server.  On the server run:

dpkg -l bluecherry

![Screen Shot 2023-02-04 at 10 23 18 AM](https://user-images.githubusercontent.com/331478/216778383-b1882819-aacf-4d0f-8aea-fc147a089fe7.png)

**Comment by dragoneye65** [comment]
||/ Name           Version      Architecture Description
ii  bluecherry     3:3.1.0-rc6  amd64        Bluecherry DVR Server

**Comment by dragoneye65** [comment]
Upgraded to 
ii  bluecherry     3:3.1.0-rc7  amd64        Bluecherry DVR Server
No change
