### ISSUE TITLE
[bug] App feezed when open

### ISSUE THREAD

**Issue by bdlukaa** [bluecherrydvr/unity#67]
#65

**Comment by bdlukaa** [comment]
Related issues:
 * https://github.com/alexmercerind/media_kit/issues/40

**Comment by pyeager56** [comment]
Just uninstalled then reinstalled beta 4.

App opens frozen - totally unresponsive.  Can only close with task manager.

![unitiy5](https://user-images.githubusercontent.com/106773418/219115927-7a245d8e-2075-40fe-b307-4cf312f1852c.PNG)

**Comment by pyeager56** [comment]
Not sure why it attempts to open 8 cameras on a fresh install.

**Comment by bdlukaa** [comment]
@pyeager56 Hello! Can you try it with the latest windows installer?

**Comment by pyeager56** [comment]
Will do, as soon as I am back in the office.  Recovering from COVID.

Paul Yeager
IT Manager
Cataloochee Ski Area
828 926 0285 ext 7321
***@***.***
________________________________

**Comment by pyeager56** [comment]
I downloaded the installer again.  Uninstalled, then reinstalled. Looks the same as the last two downloads.

Nothing has changed.

Any idea why it tries to open the cameras I had open last time it worked?

Paul Yeager
IT Manager
Cataloochee Ski Area
#thinkwinter
828 926 0285 ext 7321
800 768 0285 ext 7321
828 926 0354 fax
828 400 9442 cell

**Comment by bdlukaa** [comment]
Closing this is as completed. https://github.com/bluecherrydvr/unity/discussions/65#discussioncomment-5182619
