### ISSUE TITLE
The camera list is empty (beta5)

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/unity#77]
The camera list is empty, unless I go to settings and back:
![image](https://user-images.githubusercontent.com/1145561/222546442-449c63ad-f67f-405e-b171-7a208bbba5e7.png)

It is the same camera list used by the Events Playback

![image](https://user-images.githubusercontent.com/1145561/222546561-6e3dd3ad-fc7e-4020-8498-7dc011fd0d62.png)

As soon as I go to settings it detects the cameras:

![image](https://user-images.githubusercontent.com/1145561/222546693-49daa357-25d7-4dd4-bc84-cf0a5f0f9068.png)

And then they appear everywhere:
![image](https://user-images.githubusercontent.com/1145561/222546791-465cd80d-d491-4711-bfe4-eb172ceb543a.png)

![image](https://user-images.githubusercontent.com/1145561/222546864-8fabe694-13d7-4c82-84e6-1c9261097345.png)

_Originally posted by @guillebot in https://github.com/bluecherrydvr/unity/discussions/74#discussioncomment-5183095_

**Comment by bdlukaa** [comment]
I am thinking on a unified way to declare the server devices. Currently, we try to fetch the devices when the screen is switched, which is not ideal. Also, refresh devices at app startup
