### ISSUE TITLE
iOS (maybe Android): Time line / filtering does not populate 

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/unity#79]
See attached image

![image](https://user-images.githubusercontent.com/331478/222897757-b747806a-1e7e-4b91-9da1-7d6fd4e66299.png)

**Comment by bdlukaa** [comment]
It may be related to #77

**Comment by bdlukaa** [comment]
It looks like the app is not being able to parse the XML from the server. Still investigating
