### ISSUE TITLE
Scaling/UI - 

### ISSUE THREAD

**Issue by nicksweb** [bluecherrydvr/unity#92]
Device Info: iPhone 13, iOS 16.2
 
Love the work the BlueCherry team is doing but finding the new app difficult to work with and not quite right. I preferred the old app even though it has less features.
 
1. I found scaling and UI issues. Screenshots have been attached. Playback event window seems to small. Cannot accurately see position on timeline. Perhaps reduce the amount of information on the screen / make less cluttered. Images and buttons can be too small to accurately click. 
2. Also miss the ability to select a view and zoom in on the live image. 
3. Have also been finding the app crashes a bit can’t quite workout what’s triggering it yet. 

Happy to complete further testing. 

I will test on the latest iPad Air and also let you know how it goes. 

![74805975-B124-4144-9194-0E9BEFDBC92A](https://user-images.githubusercontent.com/12556421/230603227-ecd9e0e2-9a35-42c0-8567-cf04c8cc2095.png)
![F6751B0E-4AAE-4D2C-A6C5-278A2BB4CD83](https://user-images.githubusercontent.com/12556421/230603233-618c696b-983d-4745-9568-1338c0f8bd7f.png)
![2A140216-CF1C-4AFB-9D37-BD04C7161586](https://user-images.githubusercontent.com/12556421/230603243-4ce60cbc-c5b1-4a2b-9e7f-a2d0978be5ba.png)
![6E327411-39F6-4EDE-844F-1778CD86E09F](https://user-images.githubusercontent.com/12556421/230603246-4312915b-55ea-47d0-9ba9-e9262f75d445.png)
![F7C0EE56-EBD5-474D-BBF0-637E79EDFCC0](https://user-images.githubusercontent.com/12556421/230603250-c2cc26a9-33c7-48b7-b9b2-ce50f5a64993.png)
![FE61ED1B-37F2-4E23-95FC-A6B7F12C3C02](https://user-images.githubusercontent.com/12556421/230603258-33f4b5da-a89c-4b36-9a51-cac3adbd164a.png)

**Comment by bdlukaa** [comment]
Hello! This is weird, the UI in the screenshots are designed for the desktop version of the app. For some reason, it's being displayed in the mobile version of it. The breakpoints need to be updated once again

**Comment by bdlukaa** [comment]
> Also miss the ability to select a view and zoom in on the live image.

See #93

**Comment by nicksweb** [comment]
> > Also miss the ability to select a view and zoom in on the live image.
> 
> You can actually zoom it using your two fingers when in the full-screen view. To enter the full screen view, double tap the camera you wish or press the fullscreen button. I can reproduce some issues with it (see #93 for more info)

Great, that's works - Didn't think to try in that view!

**Comment by curtishall** [comment]
@nicksweb can you try this release?  You will need TestFlight

https://testflight.apple.com/join/GM0CxkME

**Comment by nicksweb** [comment]
Thanks I gave it a go, it does seem better - refer to support ticket on Freshdesk for screen recording.

**Comment by bdlukaa** [comment]
Most of the issues above were fixed. Here's something that has been happening lately and is related to this issue:
![image](https://github.com/bluecherrydvr/unity/assets/45696119/0a87f4c6-77e6-4046-b791-ed27c17ce7d8)
