### ISSUE TITLE
iOS SDK version warning

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/unity#95]
SDK version issue. This app was built with the iOS 16.0 SDK. Starting April 25, 2023, all iOS and iPadOS apps submitted to the App Store must be built with the iOS 16.1 SDK or later, included in Xcode 14.1 or later. (90725)

**Comment by bdlukaa** [comment]
I think that upgrading your Xcode to the latest version should do this automatically.

From https://developer.apple.com/ios/submit/:
> Please note, starting April 2023, all iOS and iPadOS apps submitted to the App Store must be built with Xcode 14.1 and the iOS 16.1 SDK.

Could you give it a go?
